Repository jumak-dev/imojumo, pull requests merged in 2023-03, with the labels that each got.

#4 [초기셋팅] css 상수 추가 및 eslint rule 추가
  .eslintrc.cjs
  src/styles/variables.tsx
Labels: setting

#16 [BUG] 🐛 CSS 컬러 상수 버그 수정
  src/styles/variables.tsx
Labels: bug

#17 [Feature] ✨ 프로그래스바 컴포넌트 개발
  src/components/UI/ProgressBar/ProgressBar.tsx
Labels: feature

#19 [Feature] ✨ 페이지네이션 컴포넌트 개발
  .eslintrc.cjs
  src/components/UI/ProgressBar/Pagination.tsx
Labels: feature

#21 [Feature] carousel 컴포넌트 개발
  src/components/UI/Carousel/Carousel.tsx
  src/components/UI/Carousel/CarouselArrowButton.tsx
  src/components/UI/Carousel/CarouselList.tsx
Labels: feature

#22 [Feature] ✨ Button 컴포넌트 개발
  src/components/UI/Button/Button.tsx
  src/components/UI/Button/ButtonPractice.tsx
  src/components/UI/Pagination/Pagination.tsx
  src/styles/GlobalStyle.tsx
Labels: feature

#23 [Feature] User Profile 개발
  src/components/UI/UserProfile/UserProfile.tsx
Labels: feature

#24 Feature/modal leehyogeun
  index.html
  src/App.tsx
  src/components/UI/Modal/ModalExample.tsx
  src/components/UI/Modal/ModalPortal.tsx
  src/components/UI/Modal/ModalTemplate.tsx
Labels: feature

#25 [Feature] Footer 컴포넌트 개발
  src/components/Layout/Footer/Footer.tsx
Labels: feature

#44 [Feature] Shared style 개발
  src/styles/GlobalStyle.tsx
  src/styles/layout.tsx
  src/styles/shared.tsx
Labels: feature

#47 [Feature] 페이지 컴포넌트, 라우터 생성
  src/App.tsx
  src/Routes/index.tsx
  src/components/Layout/index.tsx
  src/pages/BookDiscussionDetailPage.tsx
  src/pages/BookDiscussionPage.tsx
  src/pages/HomePage.tsx
  src/pages/LikeListPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/PostNewPage.tsx
  src/pages/ProConDiscussionDetailPage.tsx
  src/pages/ProConDiscussionPage.tsx
  src/pages/SearchPage.tsx
  src/pages/SignupPage.tsx
Labels: feature

#43 [Feature] Loading 컴포넌트 개발
  src/components/UI/Loading/Loading.tsx
Labels: feature

#48 [Feature] Route 파일 생성, Router 수정
  src/Routes/index.tsx
  src/Routes/route.tsx
Labels: feature
