Repository jumak-dev/imojumo, pull requests merged in 2023-05, with the labels that each got.

#89 [Feature] login기능 개발
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth.ts
  src/components/LoginSignupForm/Form.tsx
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  src/recoil/atoms.ts
  src/recoil/seletors.ts
  src/types/env.d.ts
Labels: feature

#90 [Feature] Header 컴포넌트 CSS 구현
  src/Routes/route.tsx
  src/components/Layout/Header/AlarmModal.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/ProfileModal.tsx
  src/hooks/useOnClickOutside.ts
Labels: feature

#104 [feature] camelcase 남은 부분 수정
  src/components/ProConDiscussion/ProConDiscussionCard.tsx
  src/pages/ProConDiscussionPage.tsx
  src/pages/SearchPage.tsx
Labels: bug

#102 [Feature] 독서토론 & 찬반토론 기능 구현
  src/components/ProConDiscussion/ProConDiscussionCard.tsx
  src/pages/BookDiscussionPage.tsx
  src/pages/ProConDiscussionPage.tsx
  src/types/Book.type.ts
  src/types/BookDisscussionPost.type.ts
  src/types/ProConDiscussionPost.type.ts
Labels: feature

#106 [Feature] signup 기능 구현
  src/apis/auth.ts
  src/components/LoginSignupForm/Form.tsx
  src/components/ProConDiscussion/ProConDiscussionCard.tsx
  src/constants/URL.ts
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  src/utils/auth/signupValidate.ts
Labels: feature

#112 [Feature] fetch 공통 모듈 추가, 게시글 생성 api 개발
  .env.example
  package-lock.json
  package.json
  src/apis/aladin/searchApi.ts
  src/apis/api.ts
  src/apis/imojumo/bookDisccusions.ts
  src/apis/imojumo/proConDiscussion.ts
  src/components/ErrorFallback/indes.tsx
  src/hooks/aladin/useSearchBook.ts
  src/hooks/bookDiscussion/useCreateBookDiscussion.ts
  src/hooks/proConDiscussion/useCreateProConDiscussion.ts
  src/hooks/useMutate.ts
  src/hooks/useQuery.ts
  src/types/Book.type.ts
  src/types/BookDiscussionPost.type.ts
  src/types/ProConDiscussionPost.type.ts
  src/types/env.d.ts
  src/types/index.ts
  vite.config.ts
Labels: feature

#113 [Feature] 로그인 상태 유지 기능
  src/App.tsx
  src/Routes/route.tsx
  src/components/LoginSignupForm/Form.tsx
  src/hooks/useLoggedIn.ts
  src/utils/auth/logout.ts
Labels: feature

#114 [Feature] 독서토론(상세) 화면 기능 개발
  src/apis/bookDiscussion.ts
  src/apis/comment.ts
  src/components/BookDiscussionDetail/BookInformation.tsx
  src/components/BookDiscussionDetail/DiscussionInfomation.tsx
  src/components/BookDiscussionDetail/DiscussionInformation.tsx
  src/components/Comment/CommentForm.tsx
  src/components/Comment/CommentItem.tsx
  src/pages/BookDiscussionDetailPage.tsx
  src/types/BookDiscussionPost.type.ts
  src/types/Comment.type.ts
  src/types/index.ts
Labels: feature

#115 [Feature] 홈 화면 기능 개발
  .env.example
  src/apis/aladin/searchApi.ts
  src/apis/imojumo/bookDisccusions.ts
  src/apis/imojumo/proConDiscussion.ts
  src/components/BookDiscussion/BookDiscussionCard.tsx
  src/components/Main/BookCategorySection/NewSection.tsx
  src/components/Main/BookCategorySection/NewSectionListItem.tsx
  src/components/Main/RecommendedBookCard.tsx
  src/components/Search/ProConDiscussionSearchCard.tsx
  src/hooks/aladin/useSearchBook.ts
  src/pages/BookDiscussionPage.tsx
  src/pages/HomePage.tsx
  src/pages/ProConDiscussionPage.tsx
  src/types/BookDiscussionPost.type.ts
  src/types/UseSearchAladinBook.type.ts
  src/types/env.d.ts
  src/types/index.ts
  src/utils/Rate.ts
  vite.config.ts
Labels: feature

#117 [Feature] promise 상태 타입 생성, APIError 타입 추출, onError 타입 적용
  src/apis/api.ts
  src/constants/Promise.ts
  src/hooks/useMutate.ts
  src/hooks/useQuery.ts
  src/types/Book.type.ts
  src/types/Error.type.ts
  src/types/Promise.type.ts
  src/types/index.ts
Labels: feature

#122 [Feature] 무한스크롤 패칭 기능 구현
  src/hooks/useInfiniteQuery.ts
  src/hooks/useInputs.ts
  src/hooks/useIntersectionObserver.ts
Labels: feature

#125 [Feature] 홈 화면 기능 개발
  src/Routes/route.tsx
  src/apis/aladin/searchApi.ts
  src/apis/imojumo/bookDisccusions.ts
  src/apis/imojumo/proConDiscussions.ts
  src/components/Main/Banner.tsx
  src/components/Main/BookCategorySection/NewSection.tsx
  src/components/Main/BookCategorySection/NewSectionListItem.tsx
  src/components/Main/BookCategorySection/ProConDiscussionListItem.tsx
  src/components/Main/BookDiscussionTop10.tsx
  src/components/Main/BookDiscussionTop10Card.tsx
  src/components/Main/RecommendedBookCard.tsx
  src/components/ProConDiscussion/ProConDiscussionCard.tsx
  src/components/Search/SubtitleSection.tsx
  src/components/UI/Carousel/Carousel.tsx
  src/components/UI/Carousel/CarouselList.tsx
  src/components/UI/ScrollToTop/ScrollToTop.tsx
  src/constants/Banners.ts
  src/constants/URL.ts
  src/hooks/bookDiscussion/useBookDisscussion.ts
  src/pages/HomePage.tsx
  src/styles/shared.tsx
  src/types/BookDiscussionPost.type.ts
Labels: feature

#130 [Feature] 찬반토론, 독서토론 기능 구현
  src/apis/imojumo/bookDisccusions.ts
  src/components/BookSearchModal/BookSearchListItem.tsx
  src/components/BookSearchModal/BookSearchModal.tsx
  src/components/PostNew/BookDiscussionForm.tsx
  src/components/PostNew/DiscussionInputs.tsx
  src/components/PostNew/DiscussionTab.tsx
  src/components/PostNew/PostNewForm.tsx
  src/components/PostNew/ProConDiscussionForm.tsx
  src/components/PostNew/SearchBook.tsx
  src/components/UI/NonContentModal/NonContentModal.tsx
  src/components/UI/UserProfile/UserProfile.tsx
  src/hooks/aladin/useAladinBookInfiniteQuery.ts
  src/hooks/bookDiscussion/useCreateBookDiscussion.ts
  src/hooks/proConDiscussion/useCreateProConDiscussion.ts
  src/hooks/useInfiniteQuery.ts
  src/pages/PostNewPage.tsx
  src/types/UseSearchAladinBook.type.ts
Labels: feature

#131 [But] 무한스크롤 머지 오류로 수정
  src/hooks/useInfiniteQuery.ts
Labels: bug

#133 [bug] banner 상수 , prev 동작 오류 수정
  src/components/UI/Carousel/Carousel.tsx
  src/constants/Banners.ts
Labels: bug

#140 [Feature] 독서토론(목록) 화면 기능 개발
  src/apis/imojumo/postLike.ts
  src/components/BookDiscussion/BookDiscussionCard.tsx
  src/components/UI/Pagination/Pagination.tsx
  src/hooks/bookDiscussion/useBookDisscussion.ts
  src/hooks/postLike/useCreateLike.ts
  src/hooks/postLike/useDeleteLike.ts
  src/pages/BookDiscussionPage.tsx
  src/types/BookDiscussionPost.type.ts
  src/types/Page.type.ts
Labels: feature

#143 [Feature] 찬반토론(목록) 화면 기능 개발
  src/pages/ProConDiscussionPage.tsx
Labels: feature

#142 [Feature] 홈 화면 기능 개발
  src/components/Main/BookCategorySection/NewSectionListItem.tsx
  src/components/Main/BookDiscussionTop10.tsx
  src/components/Main/BookDiscussionTop10Card.tsx
  src/pages/HomePage.tsx
Labels: feature

#137 [Feature] 찬반토론(상세) 화면 기능 개발
  src/apis/proConDiscussion.ts
  src/components/Comment/CommentForm.tsx
  src/components/Comment/CommentItem.tsx
  src/components/ProConDiscussionDetail/DiscussionInformation.tsx
  src/components/ProConDiscussionDetail/TopicDescription.tsx
  src/constants/Placeholder.ts
  src/pages/ProConDiscussionDetailPage.tsx
  src/styles/shared.tsx
Labels: feature

#147 [Feature] 토론 검색 기능 구현
  src/apis/imojumo/searchDiscussion.ts
  src/components/Layout/Header/Header.tsx
  src/components/Search/AllTab.tsx
  src/components/Search/BookDiscussionTab.tsx
  src/components/Search/EmptySearchResult.tsx
  src/components/Search/ProConDiscussionSearchCard.tsx
  src/components/Search/ProConDiscussionTab.tsx
  src/components/Search/SearchNav.tsx
  src/components/Search/SubtitleSection.tsx
  src/components/UI/Pagination/Pagination.tsx
  src/constants/PageInfo.ts
  src/hooks/searchDiscussion/useSearchDiscussion.ts
  src/hooks/useQuery.ts
  src/pages/SearchPage.tsx
  src/styles/GlobalStyle.tsx
  src/styles/layout.tsx
  src/types/Page.type.ts
  src/types/SearchDiscussion.type.ts
Labels: feature

#148 [Feature] PostNewForm 관련 폴더/파일명 수정
  src/components/BookDisscussionNewForm/BookDisscussionNewForm.tsx
  src/components/DiscussionForm/DiscussionForm.tsx
  src/components/DiscussionForm/DiscussionFormInputs.tsx
  src/components/DiscussionForm/DiscussionFormTab.tsx
  src/components/DiscussionForm/DiscussionSearchBook.tsx
  src/components/ProConDiscussionNewForm/ProConDiscussionNewForm.tsx
  src/pages/PostNewPage.tsx
Labels: feature

#150 [Feature] 도서 화면 기능 개발
  src/apis/aladin/searchApi.ts
  src/apis/imojumo/bookDetail.ts
  src/components/BookDetail/BookInformation.tsx
  src/components/BookDetail/RelatedBookDiscussion.tsx
  src/components/Search/BookDiscussionTab.tsx
  src/hooks/aladin/useAladinBook.ts
  src/hooks/bookDetail/useBookDetail.ts
  src/hooks/searchDiscussion/useSearchDiscussion.ts
  src/pages/BookDetailPage.tsx
  src/pages/SearchPage.tsx
  src/types/BookDetail.type.ts
  src/types/index.ts
  src/utils/replaceHtml.ts
Labels: feature

#153 [Refactor] 찬반/독서 토론 상세에서 fetch -> 커스텀 훅 방식 적용
  .eslintrc.cjs
  src/apis/api.ts
  src/apis/bookDiscussion.ts
  src/apis/imojumo/proConDiscussions.ts
  src/apis/proConDiscussion.ts
  src/components/BookDiscussionDetail/DiscussionInformation.tsx
  src/components/ProConDiscussionDetail/DiscussionInformation.tsx
  src/hooks/bookDiscussion/useBookDiscussionDetail.ts
  src/hooks/bookDiscussion/useDeleteBookDiscission.ts
  src/hooks/proConDiscussion/useCreateProConDiscussion.ts
  src/hooks/proConDiscussion/useDeleteProConDiscussion.ts
  src/hooks/proConDiscussion/useProConDiscussionDetail.ts
  src/hooks/proConDiscussion/useUpdateProConDiscussion.ts
  src/hooks/proConVote/useCreateProConVote.ts
  src/hooks/proConVote/useUpdateProConVote.ts
  src/pages/ProConDiscussionDetailPage.tsx
  src/types/BookDiscussionPost.type.ts
  src/types/ProConDiscussionPost.type.ts
  src/types/ProConVote.type.ts
  src/types/index.ts
Labels: refactor

#154 [Feature] 찬반 토론 기능구현, 독서 토론 수정
  src/components/BookDiscussionEditForm/BookDiscussionEditForm.tsx
  src/components/BookDiscussionNewForm/BookDiscussionNewForm.tsx
  src/components/DiscussionForm/DiscussionFormInputs.tsx
  src/components/DiscussionForm/DiscussionFormSubmitButton.tsx
  src/components/ProConDiscussionDetail/DiscussionInformation.tsx
  src/components/ProConDiscussionEditForm/ProConDiscussionEditForm.tsx
  src/components/ProConDiscussionNewForm/ProConDiscussionNewForm.tsx
  src/hooks/proConDiscussion/useProConDiscussionDetail.ts
  src/hooks/useInputs.ts
  src/pages/DiscussionEditPage.tsx
  src/pages/ProConDiscussionDetailPage.tsx
  src/types/ProConDiscussionPost.type.ts
Labels: bug, feature

#158 [Feature] rate Number 변환에서 parseInt로 수정
  src/utils/Rate.ts
Labels: feature

#159 [Feature] search css 수정
  src/components/Search/AllTab.tsx
  src/components/Search/BookDiscussionTab.tsx
  src/components/Search/ProConDiscussionTab.tsx
  src/components/Search/SubtitleSection.tsx
  src/pages/SearchPage.tsx
Labels: feature

#161 [Bug] MainContainer 에서 SearchPageMainContainer 로 수정
  src/pages/SearchPage.tsx
Labels: bug

#165 [Feature] 독서/찬반토론(상세) 댓글 커스텀 훅 적용 및 CSS 수정
  src/apis/comment.ts
  src/apis/imojumo/bookDisccusions.ts
  src/apis/imojumo/proConDiscussions.ts
  src/components/BookDiscussionDetail/BookInformation.tsx
  src/components/BookDiscussionDetail/DiscussionInformation.tsx
  src/components/Comment/CommentForm.tsx
  src/components/Comment/CommentItem.tsx
  src/components/ProConDiscussionDetail/TopicDescription.tsx
  src/hooks/bookDiscussion/useBookDiscussionDetail.ts
  src/hooks/comment/useCreateComment.ts
  src/hooks/comment/useCreateCommentDislike.ts
  src/hooks/comment/useCreateCommentLike.ts
  src/hooks/comment/useDeleteComment.ts
  src/hooks/comment/useDeleteCommentDislike.ts
  src/hooks/comment/useDeleteCommentLike.ts
  src/hooks/comment/useUpdateComment.ts
  src/hooks/proConDiscussion/useProConDiscussionDetail.ts
  src/pages/BookDiscussionDetailPage.tsx
  src/pages/ProConDiscussionDetailPage.tsx
  src/styles/shared.tsx
  src/types/Comment.type.ts
Labels: feature
